name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install exact Vite version
        run: npm install --no-save vite@5.4.19 @vitejs/plugin-react@4.3.1

      - name: Install remaining dependencies
        run: npm install --prefer-offline --no-audit

      - name: Use JS config instead of TS
        run: |
          if [ -f vite.config.ts ]; then
            mv vite.config.ts vite.config.ts.bak
          fi
          cat > vite.config.js << 'EOL'
          import { defineConfig } from 'vite';
          import react from '@vitejs/plugin-react';

          export default defineConfig({
            plugins: [react()],
            base: '/pia/',
          });
          EOL

      - name: Build project
        run: npx vite build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
